### ISSUE TITLE
Test RPMs and DEBs

### ISSUE THREAD

**Issue by mmatczuk** [saucelabs/forwarder#151]

**Comment by Choraden** [comment]
I managed to install forwarder [v1.0.0-rc0](https://github.com/saucelabs/forwarder/releases/tag/v1.0.0-rc0) on debian 11.

deb: 
 
<img width="952" alt="Screenshot 2023-01-27 at 14 16 15" src="https://user-images.githubusercontent.com/57443889/215098609-c27c2edb-ee0d-4117-a16a-b87d7e21fbdc.png">


rpm:

<img width="1027" alt="Screenshot 2023-01-27 at 14 27 54" src="https://user-images.githubusercontent.com/57443889/215098677-fe7f4053-e06c-4266-93f6-27f66dbea685.png">

**Comment by mmatczuk** [comment]
Please check the SERVICE starts.

**Comment by mmatczuk** [comment]
Check RPM on RHEL compatible distro.

**Comment by Choraden** [comment]
> Please check the SERVICE starts.

Both deb and rpm versions successfully started service on debian. 

<img width="1513" alt="Screenshot 2023-01-27 at 15 27 00" src="https://user-images.githubusercontent.com/57443889/215110659-e5b3052c-ee96-40ef-97b2-47755c0cea59.png">

**Comment by Choraden** [comment]
Installed via rpm on Fedora 37

<img width="1162" alt="Screenshot 2023-01-27 at 16 41 40" src="https://user-images.githubusercontent.com/57443889/215126964-87429a83-2896-4095-92bb-201ed98952bb.png">

**Comment by mmatczuk** [comment]
ok
