### ISSUE TITLE
forwarder proxy and forwarder proxy-eval return different results

### ISSUE THREAD

**Issue by osown** [saucelabs/forwarder#184]
The expected behaviour would be that forwarder makes a direct connection according to the PAC file, instead a connection is attempted through the proxy address. Details on the invoked commands can be found in the appendix.

PAC File
```bash
$ cat <<EOF > test.js
function FindProxyForURL(url, host) {
  if ( dnsDomainIs (host, ".google.de")) {
	return "DIRECT";
  }
  return "PROXY upstream.lan:8080";
}
EOF
```
start forwarder proxy
```bash
forwarder proxy -p ./test.js--address :8888 --verbose
```

make request
```bash
export http_proxy=http://127.0.0.1:8888
export https_proxy=http://127.0.0.1:8888
export no_proxy=localhost,127.0.0.0/8,::
curl https://www.google.de/
curl: (56) Received HTTP code 407 from proxy after CONNECT
```

### System information
Linux kali 6.0.0-kali6-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.0.12-1kali1 (2022-12-19) x86_64 GNU/Linux
go version go1.19.4 linux/amd64

### test case
[forwarder_proxy.txt](https://github.com/saucelabs/forwarder/files/10426891/forwarder_proxy.txt)
[forwarder_proxy-eval.txt](https://github.com/saucelabs/forwarder/files/10426892/forwarder_proxy-eval.txt)

**Comment by mmatczuk** [comment]
Thanks for reporting.
