### ISSUE TITLE
api: add connection state endpoint for accepted connections

### ISSUE THREAD

**Issue by mmatczuk** [saucelabs/forwarder#213]
The `/connections` endpoint returns a list of active connections, proxy or tunnel, that we accepted.
It allows to filter by type passed as a query parameter.
It supports long-polling to get to know about the new connections immediately.

Client and server synchronize on timestamp (or a logical clock).
Server sends a token in response, client presents the token on next request.

**Comment by mmatczuk** [comment]
Consider k8s long polling naming standards watch=true et al

**Comment by mmatczuk** [comment]
@waggledans why do we need it?

**Comment by waggledans** [comment]
I wonder if we need it at all. It should be added as a prom counter to be able to track in-flight connections, but it's just monitoring, I don't see a reason to add it as an endpoint

**Comment by mmatczuk** [comment]
Closing for now.
