### ISSUE TITLE
e2e: refactor for better separation of concerns and usability

### ISSUE THREAD

**Issue by mmatczuk** [saucelabs/forwarder#311]
The Forwarder e2e test framework is being used by other projects that involve Forwarder.
At the moment the structure is not great.

Proposal:
* move test code to `tests` package
* move `MakeTest` and `NewCompose` (from `run/setups`) to `e2e` because this logic corresponds to the `Makefile`
* move `service.go` and `opts.go` (from `run/setups`) to `run/forwarder`, this would enforce clear namespace for the Service specifications, and it can be used as `forwarder.ProxyService`.
* move setups generation directly to `run.go`

In addition to that `Compose.AddService` is broken and we abuse functional options pattern.

```
func (c *Compose) AddService(name, image string, opts ...ServiceOpt) {
	svc := &Service{Name: name, Image: image, Environment: map[string]string{}}
	for _, opt := range opts {
		opt(svc)
	}
	if c.Services == nil {
		c.Services = map[string]*Service{}
	}
	c.Services[name] = svc
}
```

the ServiceOpt should be replaced by real service, like that

```go
package forwarder

type Service struct {
    compose.Service
}

// Change all WithXXXX functions to SetXXXX like here

func (s *Service) SetBasicAuth(auth string) {
	s.Environment["FORWARDER_BASIC_AUTH"] = auth
}
```

**Comment by mmatczuk** [comment]
WDYT @Choraden

**Comment by Choraden** [comment]
> - move test code to `tests` package

Agree.

> - move `service.go` and `opts.go` (from `run/setups`) to `run/forwarder`, this would enforce clear namespace for the Service specifications, and it can be used as `forwarder.ProxyService`.

Good idea. 

> - move `MakeTest` and `NewCompose` (from `run/setups`) to `e2e` because this logic corresponds to the `Makefile`

It feels like `NewCompose` belongs more to the setups than to `Makefile`. `MakeTest` do corresponds to the `Makefile`, but it returns `compose.Opt`. I don't see why would we keep it in `e2e` package, as it's only purpose is in `setups` generation.  

How about a `compose/opts` package, where we would move all general purpose compose opts like:
`WithPorts`,  `WithVolume`, `WithWaitFunc`.  
We would also move the `MakeTest` there (maybe rename it to `WithMakeTest`), as it has no relationship with forwarder, it only execs `make test`.  This way we suggest users that running the test via makefile is one possible pattern. We also allow to use all the compose opts without any forwarder specific opts. 

> - move setups generation directly to `run.go`

I kind of like the idea of `setups` package. It brings a nice structure for the whole `run` package. On the other hand, this is a possible solution to stop the setups from being imported. 


When it comes to service opts I do agree that we abuse the functional pattern. Creating real services is one possible option. It will definitely bring more security to the services configuration as a user would have service type at hand. Although, I wouldn't like to give up the compactness of service declaration we have right now:

```go
ProxyService(
    WithProtocol(proxyScheme),
    WithBasicAuth("u1:p1"),
    WithGoleak(),
),
```

Let's think if we can somehow keep the lightness of a service declaration.

**Comment by mmatczuk** [comment]
We can use the builder pattern WithXXX returning a Service so that you can chain the calls.

**Comment by mmatczuk** [comment]
MakeTest can be refactored to sth more generic and I believe and moved to compose/opts
