### ISSUE TITLE
e2e: in upstream setup proxy tests should assert that upstream does proxy the traffic

### ISSUE THREAD

**Issue by mmatczuk** [saucelabs/forwarder#317]
One of the possibilities is using Via header
* add `--name` flag that defaults to hostname
* use it in proxy `httpspec.NewStack(hostname)`, this would add the name to Via header
* add test case that uses `/headers` httpbin endpoint to return the Via header, and inspects it

**Comment by mmatczuk** [comment]
Using response header can be simpler to implement. Having the flag can be a separate feature but I think it's not needed at the moment.

**Comment by Choraden** [comment]
In #327 we asserted upstream specs with http endpoint.
