### ISSUE TITLE
martian: refactor Set RoundTripper/DialContext API

### ISSUE THREAD

**Issue by Choraden** [saucelabs/forwarder#319]
Martian has an intertwined logic for setting the round tripper and the dialer. The order of calling set functions matters. DialContext needs to be set first as SetRoundTripper overwrites tr.DialContext with hp.proxy.dial.
```go
func (p *Proxy) SetRoundTripper(rt http.RoundTripper) {
	p.roundTripper = rt

	if tr, ok := p.roundTripper.(*http.Transport); ok {
		tr.TLSNextProto = make(map[string]func(string, *tls.Conn) http.RoundTripper)
		tr.Proxy = p.proxyURL
		tr.DialContext = p.dial
	}
}
```

```go
func (p *Proxy) SetDialContext(dial func(context.Context, string, string) (net.Conn, error)) {
	p.dial = func(ctx context.Context, network, addr string) (net.Conn, error) {
		c, e := dial(ctx, network, addr)
		nosigpipe.IgnoreSIGPIPE(c)
		return c, e
	}

	if tr, ok := p.roundTripper.(*http.Transport); ok {
		tr.DialContext = p.dial
	}
}
```

The API needs to be refactored as it is easy to confuse it and introduce critical bugs.

**Comment by mmatczuk** [comment]
I think we can remove setters and use fields. On start we would call init function that will perform all necessary updates.
