### ISSUE TITLE
martian: rewrite CI in GH action

### ISSUE THREAD

**Issue by mmatczuk** [saucelabs/forwarder#330]
Travis stopped running tests on our fork, we need to port the CI to GH actions.

**Comment by Choraden** [comment]
I have a controversial idea, can't help but mention it: We move martian to forwarder repo at `internal/` directory.
The fork has already diverged significantly. I doubt if we ever gonna need anything from the origin. 

Benefits: 
- no need to maintain the version dependencies
- easy access
- all tests run in CI on PRs

**Comment by mmatczuk** [comment]
Interesting.

**Comment by mmatczuk** [comment]
We could move the proxy given the nr of modifications we made.
