### ISSUE TITLE
dns: support custom servers

### ISSUE THREAD

**Issue by Choraden** [saucelabs/forwarder#331]
Golang's net.Resolver implementation does not allow to specify user-defined dns servers. One common approach is to override Resolver's Dial function. However, this is only good when using one custom server. 

When we take a look at `net` package internals we quickly discover functions and utilities that do everything we need. Unfortunately, they are hidden from user.  

When querying dns records, Golang's resolver at one point loads system dns config (read `/etc/resolv.conf` [source](https://github.com/golang/go/blob/83c4e533bcf71d86437a5aa9ffc9b5373208628c/src/net/dnsclient_unix.go#L351)) into the following dnsConfig struct:
```go
type dnsConfig struct {
	servers       []string      // server addresses (in host:port form) to use
	search        []string      // rooted suffixes to append to local name
	ndots         int           // number of dots in name to trigger absolute lookup
	timeout       time.Duration // wait before giving up on a query, including retries
	attempts      int           // lost packets before giving up on server
	rotate        bool          // round robin among servers
	unknownOpt    bool          // anything unknown was encountered
	lookup        []string      // OpenBSD top-level database "lookup" order
	err           error         // any error that occurs during open of resolv.conf
	mtime         time.Time     // time of resolv.conf modification
	soffset       uint32        // used by serverOffset
	singleRequest bool          // use sequential A and AAAA queries instead of parallel queries
	useTCP        bool          // force usage of TCP for DNS resolutions
	trustAD       bool          // add AD flag to queries
	noReload      bool          // do not check for config file updates
}
```
The struct is later stored in global yet private variable `resolveConf` that is used by all the queries.
The idea is to link the private function `getSystemDNSConfig()` to forwarder's package to load the dnsConfig and set the values accordingly.
 This way we can provide custom servers, timeouts, and even specify to round robin among the servers. 

We must remember about setting `noReload` flag, so that the config won't get reloaded.

**Comment by mmatczuk** [comment]
This can also cause some race conditions so we need to be extra careful.
