### ISSUE TITLE
martian: replace log with forwarder/log

### ISSUE THREAD

**Issue by mmatczuk** [saucelabs/forwarder#351]
Needed for #69 to provide context to logs. 

In #350 we ingested the Martian code internally.
I suggest we replace the `log` package with a `log` variable (of type [log.Logger](https://github.com/saucelabs/forwarder/blob/ccc178d566691bc8ec822595136e2e81f714e3ed/log/log.go#L10)) to limit the scope of the change, and adapt the context parameter.

**Comment by Choraden** [comment]
Martian has a global logger of type log.Logger. This was changed in f1b7666.
