### ISSUE TITLE
martian: improve handling of round trip errors

### ISSUE THREAD

**Issue by mmatczuk** [saucelabs/forwarder#486]
If round-trip error occurs: 
* If body size is known drain the body, (and read next request)
* Else, close connection after writing proxy error response.

**Comment by Choraden** [comment]
As of my knowledge readTransfer[1] (http.ReadRequest) creates http.Request with a body that would be drained on close[2]. 

Do we need to implement the draining mechanism then? 

[1] https://go.dev/src/net/http/transfer.go#L486
[2] https://go.dev/src/net/http/transfer.go#L802

**Comment by mmatczuk** [comment]
The problem is `defer req.Body.Close()`. If body close fails we must close the connection. Now we do not even return the error.
