### ISSUE TITLE
mitm: handle upstream proxy error responses for CONNECT requests 

### ISSUE THREAD

**Issue by Choraden** [saucelabs/forwarder#510]
When HTTP client fails HTTPS CONNECT request, it does not return the original response, but an error.

**Comment by mmatczuk** [comment]
Idea:

Use http.Transport with dedicated dialer using DialVia instead of ProxyURL.
On error return specialized error that contains the http.Response or it's representation.

**Comment by mmatczuk** [comment]
Now Transport has 

```
	// OnProxyConnectResponse is called when the Transport gets an HTTP response from
	// a proxy for a CONNECT request. It's called before the check for a 200 OK response.
	// If it returns an error, the request fails with that error.
	OnProxyConnectResponse func(ctx context.Context, proxyURL *url.URL, connectReq *Request, connectRes *Response) error
```

**Comment by mmatczuk** [comment]
When MITM is enabled and there is an upstream proxy that returns invalid HTTP response for CONNECT request we fail to properly handle it and we return http status code 500.

```
HTTP/1.1 500 Internal Server Error
Content-Length: 80
Content-Type: text/plain; charset=utf-8
X-Forwarder-Error: forwarder proxy connect error: 304 Not Modified
```

**Comment by mmatczuk** [comment]
One thing to note here is that there is a design issue. 
In MITM mode consume the connect request and reply HTTP 200 at all times.
Then we fallback to normal handle() using the MITMed connection.
This is inherited from the original code and tbh has many benefits like allowing different transports to handle requests.

For purity we should be passing the upstream connect error.
