### ISSUE TITLE
Add metric for dialed connections

### ISSUE THREAD

**Issue by mmatczuk** [saucelabs/forwarder#514]
We need metric for 
* total dialed connections
* active outgoing connections 
* total accepted connections
* active incoming connections

**Comment by Choraden** [comment]
Similar to #118.

**Comment by mmatczuk** [comment]
I want to instrument dials too. How long dial took, and if there was any errors.

**Comment by mmatczuk** [comment]
Dials should be labeled if they go to upstream proxy with the proxy name.
