### ISSUE TITLE
windows: support installation with package manager

### ISSUE THREAD

**Issue by mmatczuk** [saucelabs/forwarder#563]
Scoop is brew for Windows 

Useful links:
* https://scoop.sh/
* https://goreleaser.com/customization/scoop/

**Comment by Choraden** [comment]
Use https://goreleaser.com/customization/chocolatey/ instead of scoop.

**Comment by mmatczuk** [comment]
After investigating the available options I think that [winget](https://learn.microsoft.com/en-us/windows/package-manager/winget/) the Windows builtin package manager is a way to go.

First of all it's installed by default in W10 and W11, second of all there is a lively maintained [repository of community packages](https://github.com/microsoft/winget-pkgs) that's available to all users.

Private repositories are possible but adding a new source requires admin access that may be prohibitive for many users working on a company laptop.

**Comment by mmatczuk** [comment]
On technical side of things Choco GoReleaser integration requires the choco binary to be installed. This implies Windows but can be worked around by running choco over mono [like in this example](https://github.com/faabiosr/rand-beer/blob/4200fe39873cf835c757b065068e39a525ab129a/.github/workflows/release.yml#L17).

Interesting choco contains an independent package for sauce-connect up to version 4.7 https://community.chocolatey.org/packages/sauce-connect#versionhistory.

**Comment by mmatczuk** [comment]
I sent a patch to add Forwarder 1.2.1 https://github.com/microsoft/winget-pkgs/pull/156504 before automating it.

**Comment by mmatczuk** [comment]
I added a fork https://github.com/saucelabs/winget-pkgs with `forwarder` branch reset to my commit in the PR linked in my prev comment. It is intended to host all our winget changes, but one needs to create PR to the upstream manually.
