### ISSUE TITLE
perf: use go routine pooling

### ISSUE THREAD

**Issue by mmatczuk** [saucelabs/forwarder#663]
As we know from metrics Forwarder can be heavy on Go routines.

I suggest we use a go routine pool, more specifically https://github.com/panjf2000/ants - one of more mature implementation - it is used in gnet project.

Using gnet is out to scope at this point, it does not support TLS among other things.

**Comment by Choraden** [comment]
#796 has shown that ants give little to no improvement in CPU/memory usage, while increasing code complexity and adding a dependency. 
It might be that the go runtime has improved or Forwarder is smart enough not to waste resources, so that the runtime has room for seamless handling of goroutines.
