### ISSUE TITLE
proxy: localhost proxying exposes proxy local services

### ISSUE THREAD

**Issue by mmatczuk** [saucelabs/forwarder#76]
When `ProxyLocalhost` is disabled, user can call services listing on localhost on the proxy machine.
This is exactly what we can see in #31 logs, local proxy does not hit upstream, instead it uses its own localhost to deliver the result.

Related to #31

**Comment by alexh-sauce** [comment]
There's some history here with the old SC client behaviour. Originally it would always pass requests to the parent proxy, regardless of hostname. Users were most often confused when they were using a parent proxy for resources in their network, but actually testing an app running on `localhost`. We left it configurable in case anyone was relying on the broken behaviour, but if someone was relying on accessing a proxy's localhost interface, why not just access it directly?

**Comment by mmatczuk** [comment]
The point is that it should be disabled by default, and if needed enabled. If it is disabled it would still work and try to use it's own localhost while it should report an error and fail.
