### ISSUE TITLE
Websockets do not connect on first attempt on Firefox

### ISSUE THREAD

**Issue by pulsejet** [saucelabs/forwarder#938]
## Expected Behavior

Websockets work

## Actual Behavior

The first connection to websocket on loading a page fails, but the second one succeeds. Refresh the page and this happens again.

## Steps to Reproduce the Problem

  1. Set up forwarder+proxy in Firefox
  1. Go to https://websocketking.com/
  1. Click "Connect". It fails.
  1. Click "Connect" again. It connects now.

## Specifications

  - Version: 1.36.2
  - Platform: Windows Firefox 125

![{A884EBF0-7BE3-4482-AC31-EE47BECE2D14}](https://github.com/user-attachments/assets/a088df3d-1795-45d6-af52-2fdb244fa792)
![{7569F0A7-D266-4C1E-B044-C439FD8B109B}](https://github.com/user-attachments/assets/20b7b117-e241-4215-9ab0-3dda3953913f)
![{A659E9BA-BD10-4D06-B9CD-8000CBB30911}](https://github.com/user-attachments/assets/dd654153-7ea6-4250-8903-0e4d16b4f972)

**Comment by mmatczuk** [comment]
Nice find. It work with MITM, it does not work without MITM.

**Comment by mmatczuk** [comment]
What happens is that the FF is interpreting the connect response as server response.
