### ISSUE TITLE
systemctl restart and systemctl stop seems to hang on ubuntu 24.04 if websockets are in use

### ISSUE THREAD

**Issue by rmah** [saucelabs/forwarder#960]
## Expected Behavior

Executing `sudo systemctl restart forwarder` should stop the deamon and disconnect any clients immediately and restart even if websocket connections are active.

## Actual Behavior

Executing it will hang as long as all websocket clients are active.  We get the same behavior with or `sudo systemctl stop forwarder`.
After all websocket clients are closed, forwarder restarts/stops.

Note: the vast majority of sites using websockets have auto-reconnect handlers in place because websocket streams are so unreliable.

## Steps to Reproduce the Problem

  1. Run forwarder on a proxy server
  2. Setup proxy in web browser to use the proxy server
  3. Connect to a website using websockets
  4. Try to execute `sudo systemctl restart forwarder` (or `sudo systemctl stop forwarder`) on the proxy server
  5. Watch nothing happen :-)

## Specifications

  - Version: v1.3.2
  - Platform: Ubuntu 24.04
  - Subsystem:

**Comment by mmatczuk** [comment]
It tries to drain the connections, we'll look into this.
